### ISSUE TITLE
Add support and instructions for Let's Encrypt service

### ISSUE THREAD

**Issue by Krillsson** [Krillsson/sys-api#11]
Because SSL should be default.

Tutorial:
https://nbsoftsolutions.com/blog/dropwizard-1-1-and-lets-encrypt-with-no-downtime

Code changes needed:
https://github.com/bazaarvoice/dropwizard-configurable-assets-bundle/blob/master/src/main/java/com/bazaarvoice/dropwizard/assets/ConfiguredAssetsBundle.java

Handy command to create jks:
`$ openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -out /home/dropwizard/cert/pkcswww.p12 -name cert -password pass:<password>
keytool -deststorepass <password> -importkeystore -destkeypass <password> -destkeystore keystorewww.jks -srckeystore /home/dropwizard/cert/pkcswww.p12 -srcstoretype PKCS12 -srcstorepass <password> -alias cert`

configuration.yml changes (not sure if valid):
```
assets:
 overrides:
   /.well-known/acme-challenge: ./acme/.well-known/acme-challenge
server:
 rootPath: /v1/*
 applicationConnectors:
   - type: http
     port: 80
   - type: https
     port: 443
     keyStorePath: ./cert/keystorewww.jks
     keyStorePassword: <password>
     validateCerts: false
     validatePeers: false
```
