### ISSUE TITLE
Error and load 

### ISSUE THREAD

**Issue by cookins** [Krillsson/sys-API#121]
Hey again.
Great, I'm happy that i found it. Bit it's a bit load RAM... Maybe there something can be turned off, to lower RAM load?
![Screenshot_2023-09-06-21-57-54-658_com.krillsson.monitee.jpg](https://github.com/Krillsson/sys-API/assets/7893051/938d2de1-f5a6-47ac-9627-46553ecff77b)

Another one - i getting error for nginx.log. I'm not have it installed, as i recall.
![IMG_20230906_220738.jpg](https://github.com/Krillsson/sys-API/assets/7893051/2c8be486-4df5-452c-96c4-f92b160296a1)

**Comment by Krillsson** [comment]
For RAM usage: can you set cache to false? Line 17 in configuration.yml

```yml
  cache:
    enabled: false
    duration: 5
    unit: SECONDS
```

**Comment by Krillsson** [comment]
For nginx error. It's because I left it in there as a sample. A mistake on my end

Can you change this (line 77)

```yaml
logReader: 
   files: 
     - /var/log/nginx/access.log
```

To this

```yaml
logReader:
   files: []
```
