### ISSUE TITLE
[HELP] * Unrecognized field at: docker.cache

### ISSUE THREAD

**Issue by jfromeo** [Krillsson/sys-API#135]
OMV 7 running on debian 12, with docker-ce 25.0.3 installed

Just created the sys-api container with default config (created the volume folders /data and /config on my server), put default configuration.yml into /config, but I got the following error after deploying

```
io.dropwizard.configuration.ConfigurationParsingException: /config/configuration.yml has an error:
  * Unrecognized field at: docker.cache
    Did you mean?:

      - host
      - enabled
```

That part stands as it follows in the configuration.yml file:

```
docker:
  enabled: true
  cache:
    enabled: true
    duration: 2
    unit: SECONDS
  # uncomment if you'd like to manually specify docker host
  # host: unix://
```

Thanks in advance and sorry beforehand as I am not an IT guy.
