### ISSUE TITLE
[HELP] * Unrecognized field at: docker.cache

### ISSUE THREAD

**Issue by connorshinn** [Krillsson/sys-API#136]
Having the same issue that [jfromeo](https://github.com/jfromeo) posted about earlier: https://github.com/Krillsson/sys-API/issues/135. 
He had closed the issue, but it sounds like myself and at least one other person are still encountering the problem so wanted to re-open. 

Context: 

- Attempting to run in Docker container using provided docker-compose and configuration.yml files (both have been updated to reflect my system). 
- Can confirm configuration.yml file is in /config
- When trying to start the container, I get the following error:

```
io.dropwizard.configuration.ConfigurationParsingException: /config/configuration.yml has an error:
  * Unrecognized field at: docker.cache
    Did you mean?:

      - host
      - enabled
```
- Relevant section of the configuration.yml file currently reads: 

```
docker:
  enabled: true
  cache:
    enabled: true
    duration: 2
    unit: SECONDS
  # uncomment if you'd like to manually specify docker host
  # host: unix:///var/run/docker.sock or unix:///run/podman/podman.sock
```

Any advice would be much appreciated!

**Comment by Krillsson** [comment]
so sorry for this @connorshinn, @jfromeo and @arpanghosh8453. It's because the config file in this git repo has features that the one on docker hub don't have yet.

Comment out the cache part like I've done below

```yaml
docker:
  enabled: true
#  cache:
#    enabled: true
#    duration: 2
#    unit: SECONDS
```
