### ISSUE TITLE
Unraid

### ISSUE THREAD

**Issue by fushi-5** [Krillsson/sys-API#177]
Hello good.
How to set up on an unraid.
Thank you.

**Comment by Krillsson** [comment]
I run unraid myself. I use the [docker compose plugin](https://forums.unraid.net/topic/114415-plugin-docker-compose-manager/) and then you can use the compose file below.

Make sure to also create the appropriate directories and download the configuration.yml first.

Assuming /mnt/user/appdata is your docker/appdata directory:

```sh
mkdir /mnt/user/appdata/sys-api/data
mkdir /mnt/user/appdata/sys-api/config
cd /mnt/user/appdata/sys-api/config
wget https://raw.githubusercontent.com/Krillsson/sys-API/refs/heads/master/config/configuration.yml
nano configuration.yml
```


```yml
services:
  sys-api:
    container_name: sys-api
    # krillsson/sys-api:native to try the native build
    image: krillsson/sys-api:latest
    # exposes NIC's for sys-API to read
    network_mode: host
    # Uncomment if you don't want to run in network_mode: host
    # ports:
    # - "8080:8080"
    # - "8443:8443"
    #  # port for docker management API.
    # - "2375:2375"
    # expose host processes for container.
    pid: "host"
    volumes:
      # change "/path/to/*" point to a directory on your machine
      - /mnt/user/appdata/sys-api/data:/data
      - /mnt/user/appdata/sys-api/config:/config
      # socket for docker management API.
      - /var/run/docker.sock:/var/run/docker.sock
      # to read device names from disks
      - /run/udev:/run/udev:ro
      # to allow sys-API access to read hdd's
      # alternatively mount in each device you'd like to monitor
      - /dev:/dev:ro
      - /mnt:/mnt:ro
      # mount in log dir. Has to be passed in configuration.yml
      - /var/log:/var/log:ro
    restart: unless-stopped
```
