### ISSUE TITLE
Using docker 

### ISSUE THREAD

**Issue by progressify** [Krillsson/sys-API#52]
It's possibile run this application in a docker container? 🤔

**Comment by Krillsson** [comment]
@progressify you can always try. But since docker is a virtualization environment, it would mean that the server would report whatever the linux build inside of the specific docker container would say. That kinda defeats the purpose of this application :)

You could look into if https://github.com/oshi/oshi supports being run inside a docker container.

**Comment by progressify** [comment]
if I use in docker-compose this tag? 
```
cap_add:
  - ALL
```

**Comment by Krillsson** [comment]
@progressify turns out I have misunderstood what Docker is. A docker container is not a virtual machine.

I will look into docker support. As I would benefit from it myself.

**Comment by Krillsson** [comment]
Resources:

https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#jib-extensions
https://github.com/GoogleContainerTools/jib/tree/master/examples/dropwizard
https://github.com/rafael1886/dropwizard-sample/tree/406cbaed74263c1b13773ef46fa931e4a66b2ef1

Planning to have volumes where `data/` has the .json and keystore files and `/config` has _configuration.yml_. So those can be kept outside of the container.

**Comment by progressify** [comment]
in the readme this link is offline: https://dropwizard.github.io/dropwizard/manual/configuration.html

related to docker, I image every setting of the configuration.yml as env var to set, and the container at first startup will build the configuration.yml file

**Comment by poornachandratejasvi** [comment]
Eagerly waiting for docker support

**Comment by Krillsson** [comment]
@progressify been thinking about this some more. Dropwizard support inputting arguments, so if I setup the container to start the application and pass environment variables into it. And then inside sys-API, if there is an argument that gets priority over the config file. Will this support your use case?

This way I don't have to maintain a templated config alongside my regular config.

What are your thoughts? I haven't started reading up on creating docker images yet, are there any aspect I'm missing?

**Comment by Krillsson** [comment]
> @progressify been thinking about this some more. Dropwizard support inputting arguments, so if I setup the container to start the application and pass environment variables into it. And then inside sys-API, if there is an argument that gets priority over the config file. Will this support your use case?
> 
> This way I don't have to maintain a templated config alongside my regular config.
> 
> What are your thoughts? I haven't started reading up on creating docker images yet, are there any aspect I'm missing? 

Scrap this. I took another read inside [here](https://github.com/GoogleContainerTools/jib/tree/master/examples%2Fdropwizard) and it looks like this can be made to work using Gradle. Since I saw a bunch of maven in there i thought it only worked using maven.

**Comment by progressify** [comment]
I don't know how dropwizard works, but my idea was this:
- I will pass the env var of configurations to the container
- the container will start and create for me the configuration file
- after this, the application starts and read the conf file

Is this logic applicable?

**Comment by Krillsson** [comment]
From reading this [reddit thread](https://www.reddit.com/r/docker/comments/mkptsz/what_is_the_standard_way_to_pass_configuration/), it seems that both options are considered "valid".

I prefer binding a volume with the config file over [building a templated config](https://github.com/GoogleContainerTools/jib/blob/master/examples/dropwizard/src/main/resources/dropwizard.yml). If I create an ENV var for each setting, there will be a lot of ENV vars. This is what I'm used to from images such as [home assistant](https://www.home-assistant.io/installation/linux#docker-compose)

By the looks of [this stackoverflow](https://stackoverflow.com/questions/40873165/use-docker-run-command-to-pass-arguments-to-cmd-in-dockerfile), it looks like I can support your use case as well. Perhaps I will slim down the amount of ENV vars though.

**Comment by Krillsson** [comment]
I pushed a image to https://hub.docker.com/r/krillsson/sys-api that you can try.

As I suspected, for instance the processes returns only 1 process, and that is the sys-api itself. And the container management support blew up. Will see if I can work out these kinks.

**Comment by Krillsson** [comment]
Looks like you can pass --pid="host" to mitigate it (and loosen on the security). I can add this and the volumes stuff to a docker-compose.yml

**Comment by Krillsson** [comment]
Worked out all the kinks now. We should be good to go with containerized sys-API ☺️

Good resource for learning docker compose: https://docs.linuxserver.io/general/docker-compose

_docker-compose.yml_: 
```yaml
version: "3"
services:
  sys-api:
    command:
      - server
      - /config/configuration.yml
    container_name: sys-api
    entrypoint:
      - java
      - -cp
      - /resources:/classes:/libs/*
      - com.krillsson.sysapi.SysAPIApplication
    environment:
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - JAVA_HOME=/opt/java/openjdk
      - JAVA_VERSION=jdk8u322-b06
      - LANG=en_US.UTF-8
    image: krillsson/sys-api:latest
    ports:
      - "8080:8080"
      - "8443:8443"
      # port for docker management API.
      # remove if you don't need docker management support
      - "2375:2375"
    # expose host processes for container. 
    # Without it container only sees its internal processes
    pid: "host"
    volumes:
      - /Users/krillsson/IdeaProjects/sys-API/server/data:/data
      - /Users/krillsson/IdeaProjects/sys-API/server/src/dist/config:/config
        # socket for docker management API.
        # remove if you don't need docker management support
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```

**Comment by Krillsson** [comment]
@progressify and @poornachandratejasvi docker image should be stable now. Mind giving it a go?

**Comment by progressify** [comment]
Today I will test and I'll give you feedbacks :)

**Comment by progressify** [comment]
Today I will test and I'll give you feedbacks :)

**Comment by progressify** [comment]
how I can disable HTTPS in the container? 🤔

**Comment by progressify** [comment]
how I can disable HTTPS in the container? 🤔

**Comment by Krillsson** [comment]
If you want to disable exposing of https port, simply run the docker compose file again but remove the row:

      - "8443:8443"

**Comment by Krillsson** [comment]
You can also disable https in sys-API completely. But that's not necessary?

**Comment by progressify** [comment]
```
sys-api    | io.dropwizard.configuration.ConfigurationValidationException: /config/configuration.yml has the following errors:
sys-api    |   * connectivityCheck must not be null
sys-api    |   * metricsConfig must not be null
```

Have you a default schema of the fields to insert in the configurations.yml?

**Comment by progressify** [comment]
```
sys-api    | io.dropwizard.configuration.ConfigurationValidationException: /config/configuration.yml has the following errors:
sys-api    |   * connectivityCheck must not be null
sys-api    |   * metricsConfig must not be null
```

Have you a default schema of the fields to insert in the configurations.yml?

**Comment by Krillsson** [comment]
Please copy paste https://github.com/Krillsson/sys-API/blob/master/server/src/dist/config/configuration.yml

And make your changes again.

**Comment by progressify** [comment]
ok it works well!
I use Traefik as a reverse proxy and this is the `docker-compose.yml` that I have used.

```
version: "3"

services:

  sys-api:
    command:
      - server
      - /config/configuration.yml
    container_name: sys-api
    entrypoint:
      - java
      - -cp
      - /resources:/classes:/libs/*
      - com.krillsson.sysapi.SysAPIApplication
    environment:
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - JAVA_HOME=/opt/java/openjdk
      - JAVA_VERSION=jdk8u322-b06
      - LANG=en_US.UTF-8
    image: krillsson/sys-api:latest
    pid: "host"
    volumes:
      - ./data:/data
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sysapi.entrypoints=websecure"
      - "traefik.http.routers.sysapi.rule=Host(`<your-domain-name>`)"
      - "traefik.http.routers.sysapi.tls.certresolver=lets-encr"
      - "traefik.http.services.sysapi.loadbalancer.server.port=8080"
    restart: always

networks:
  default:
    external:
      name: <your-traefik-net>
```

replace:
- `<your-domain-name>` with your subdomains
-  `<your-traefik-net>` with the name of your traefik installation

**Comment by progressify** [comment]
ok it works well!
I use Traefik as a reverse proxy and this is the `docker-compose.yml` that I have used.

```
version: "3"

services:

  sys-api:
    command:
      - server
      - /config/configuration.yml
    container_name: sys-api
    entrypoint:
      - java
      - -cp
      - /resources:/classes:/libs/*
      - com.krillsson.sysapi.SysAPIApplication
    environment:
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - JAVA_HOME=/opt/java/openjdk
      - JAVA_VERSION=jdk8u322-b06
      - LANG=en_US.UTF-8
    image: krillsson/sys-api:latest
    pid: "host"
    volumes:
      - ./data:/data
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sysapi.entrypoints=websecure"
      - "traefik.http.routers.sysapi.rule=Host(`<your-domain-name>`)"
      - "traefik.http.routers.sysapi.tls.certresolver=lets-encr"
      - "traefik.http.services.sysapi.loadbalancer.server.port=8080"
    restart: always

networks:
  default:
    external:
      name: <your-traefik-net>
```

replace:
- `<your-domain-name>` with your subdomains
-  `<your-traefik-net>` with the name of your traefik installation
